# Generated by Django 4.0.1 on 2022-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_vacance_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('yandexloc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
