# Generated by Django 4.0.1 on 2022-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_galary_mp_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='image',
            field=models.ImageField(upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='image',
            field=models.ImageField(upload_to='MP'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='store'),
        ),
        migrations.AlterField(
            model_name='vacance',
            name='image',
            field=models.ImageField(upload_to='vacance'),
        ),
    ]
