# Generated by Django 4.0.1 on 2022-02-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0004_alter_galary_image_alter_mp_image_alter_store_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='podstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='store')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.store', verbose_name='Выбрать категорию')),
            ],
        ),
    ]
