# Generated by Django 4.0.1 on 2022-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0005_podstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podstore',
            name='image',
            field=models.ImageField(upload_to='forstore'),
        ),
    ]
