# Generated by Django 4.0.1 on 2022-02-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0006_alter_podstore_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='podstore',
            new_name='store_chapter',
        ),
    ]
