# Generated by Django 4.0.1 on 2022-02-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0007_rename_podstore_store_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_chapter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stch', to='lol.store', verbose_name='Выбрать категорию'),
        ),
    ]
