# Generated by Django 4.0.1 on 2022-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0009_alter_store_chapter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sername', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
