# Generated by Django 4.0.1 on 2022-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0011_regmp_delete_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ame', models.CharField(max_length=20)),
                ('sername', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
