# Generated by Django 4.0.1 on 2022-02-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0012_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ame',
            new_name='name',
        ),
    ]
