# Generated by Django 4.0.1 on 2022-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0013_rename_ame_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('sername', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('place', models.IntegerField()),
            ],
        ),
    ]
