# Generated by Django 4.0.1 on 2022-04-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0020_rename_colot_text_for_main_color_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='for_main',
            old_name='color_text',
            new_name='colot_text',
        ),
    ]
