# Generated by Django 4.0.1 on 2022-04-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0021_rename_color_text_for_main_colot_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='for_main',
            old_name='colot_text',
            new_name='color_text',
        ),
    ]
