# Generated by Django 4.0.1 on 2022-04-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0022_rename_colot_text_for_main_color_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='for_main',
            name='color_text',
        ),
    ]
