# Generated by Django 4.0.1 on 2022-04-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0023_remove_for_main_color_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='for_main',
            name='color_background',
        ),
        migrations.RemoveField(
            model_name='for_main',
            name='image',
        ),
        migrations.RemoveField(
            model_name='for_main',
            name='text',
        ),
    ]
