# Generated by Django 4.0.1 on 2022-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0025_for_main_color_background_for_main_color_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dla_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='for_main')),
                ('color_background', models.CharField(max_length=20)),
                ('color_text', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
