# Generated by Django 4.0.1 on 2022-04-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0026_dla_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dla_main',
        ),
    ]
