# Generated by Django 4.0.1 on 2022-04-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0027_delete_dla_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='for_main',
        ),
    ]
