# Generated by Django 4.0.1 on 2022-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0028_delete_for_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='for_main')),
                ('color_background', models.CharField(max_length=20, null=True)),
                ('color_text', models.CharField(max_length=20, null=True)),
                ('heading', models.CharField(max_length=20, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
