# Generated by Django 4.0.1 on 2022-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0029_for_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_main',
            name='color_background',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='for_main',
            name='color_text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='for_main',
            name='heading',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='for_main',
            name='image',
            field=models.ImageField(upload_to='for_main'),
        ),
        migrations.AlterField(
            model_name='for_main',
            name='text',
            field=models.TextField(),
        ),
    ]
