# Generated by Django 4.0.1 on 2022-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0030_alter_for_main_color_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
