# Generated by Django 4.0.1 on 2022-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0032_alter_galary_title_alter_store_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_chapter',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
