# Generated by Django 4.0.1 on 2022-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0033_alter_store_chapter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_chapter',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
